google_analytics: UA-562876-12
markdown: kramdown
highlighter: rouge
defaults:
- scope:
    path: "fr"
  values:
    layout: "default"
    lang: "fr"
    weight: 100
- scope:
    path: "en"
  values:
    layout: "default"
    lang: "en"
    weight: 100
- scope:
    path: "README.md"
  values:
    weight: 0
- scope:
    path: "en/README.md"
  values:
    weight: 0
- scope:
    path: "fr/README.md"
  values:
    weight: 0
- scope:
    path: "en/account-list.md"
  values:
    weight: 1
- scope:
    path: "fr/account-list.md"
  values:
    weight: 1
- scope:
    path: "en/account-edition.md"
  values:
    weight: 2
- scope:
    path: "fr/account-edition.md"
  values:
    weight: 2